# Generated by Django 4.0.1 on 2023-02-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(default=None),
        ),
    ]
